map $host $bitrix_document_root {
    hostnames;
    default /opt/www/public_html;
    dev.finntrail.ru /opt/www/dev/public_html;
    dev1.finntrail.ru /opt/www/dev1/public_html;
    dev2.finntrail.ru /opt/www/dev2/public_html;
}
